const { chromium } = require('playwright');
const [out, file] = process.argv.slice(2);
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => { const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 400, height: 866 }, deviceScaleFactor: 2.5 });
await c.addInitScript(() => localStorage.setItem('vaultr-notif-skip', '1'));
const p = await c.newPage(); await p.goto('file://' + file); await wait(3000);
await p.click('[data-demo-login="demo_lea"]'); await wait(1500);
await p.click('[data-tab="wallet"]'); await wait(300); await p.click('[data-open="mise"]'); await wait(300);
await p.locator('#miseRange').fill('50'); await p.dispatchEvent('#miseRange', 'input'); await wait(200); await p.click('#miseOk'); await wait(800);
await p.evaluate(() => { const k = 'vaultr-v3-demo-v1', d = JSON.parse(localStorage.getItem(k)); d['programs/demo_lea'].tasks[1].value = 30; localStorage.setItem(k, JSON.stringify(d)); });
await p.reload(); await wait(3200); await p.locator('[data-act="resume"]').click({ timeout: 2500 }).catch(() => {}); await wait(1500);
await p.click('#roleSwitch [data-role="coach"]'); await wait(1200);
await p.click('[data-tab="clients"]'); await wait(300); await p.click('[data-client="demo_lea"]'); await wait(400);
await p.click('[data-validate] >> nth=1'); await wait(500);
await p.click('#roleSwitch [data-role="athlete"]'); await wait(2800); await p.screenshot({ path: out + '/cele30.png' });
console.log(await p.textContent('.cele-card'));
await b.close(); })();
